### ISSUE TITLE
Proposition d'amélioration

### ISSUE THREAD

**Issue by tioneb79** [ltoinel/amw#1]
bonjour, c'est pour moi très intéressant ! 
au lieu de rechercher par un ID précis, pourrait-on imaginer rechercher un produit par son nom lors de l'appel du script et que l'API d'amazon nous renvoie les résultats et dispo/prix/prime ?

**Comment by ltoinel** [comment]
Fonctionnalité développée sur la release 1.1 pour prendre en compte l'affichage de widget en se basant sur le nom du produit.
